import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { getTeamMatches } from '../lib/team';
import styles from '../styles/Home.module.css';

interface IMatch {
  team1: string;
  score: string;
  team2: string;
}

const Home: NextPage = () => {
  const [matches, setMatches] = useState<IMatch[]>([]);

  const fetchTeams = async () => {
    const teamMatches = await getTeamMatches();
    setMatches(teamMatches);
  };

  useEffect(() => {
    fetchTeams();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!matches.length ? (
          <h1>Loading Matches...</h1>
        ) : (
          matches.map((match, index) => (
            <div
              key={index}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <span>{match.team1}</span>
              <span>{match.score}</span>
              <span>{match.team2}</span>
            </div>
          ))
        )}
      </main>
    </div>
  );
};

export default Home;
